# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel:
    - releng-notify

github:
  delete_branch_on_merge: true
  version_tag_format: "v{{version}}"
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  major_bump_labels:
    - "Expeditor: Bump Major Version"

pipelines:
  - verify:
      public: true

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Expeditor: Skip Version Bump"
        - "Expeditor: Skip All"
  - bash:.expeditor/update_readme.sh:
      only_if: built_in:bump_version
  - built_in:update_changelog:
      ignore_labels:
        - "Expeditor: Skip Changelog"
        - "Expeditor: Skip All"
